### ISSUE TITLE
Creating a GTM Tag and the trigger for e-commerce tracking

### ISSUE THREAD

**Issue by Serge-Wiki** [magepal/magento2-google-tag-manager#25]
Hello everybody, 

I’m new to GTM data layers and would like to enable e-commerce tracking on my Magento 2 website. I’ve installed the extension and it seems that it generates data layer on my “Thank you page”. As far as I know in order to send my data to Google Analytics I have to create a tag and fire it on custom event trigger that should be generated inside the data layer. For example, it should be something like event: “Thankyou-success” or something like that.
When I look through the code in JS console of Chrome I don’t see this line of code, just Event: “gtm-dom” and Event: “gtm.js” but those events appear on all pages of my site.
So what event should I choose or should I create a trigger related to the page type? If so how can I do this?

Thanks
![gtm](https://user-images.githubusercontent.com/31511015/29973298-c5c2d696-8f37-11e7-933d-501330d8d9c1.png)

**Comment by srenon** [comment]
@Serge-Wiki ... Take a look at 'Standard Ecommerce'  https://support.google.com/tagmanager/answer/6107169?hl=en

**Comment by Serge-Wiki** [comment]
Thanks for the link. So I’ve created the tag with Data layer check box. Does it mean that now under E-commerce section of Google Analytics I will see all the e-commerce data? How will I define the event of completing the order?

Thanks a lot

**Comment by gediminaskv** [comment]
@Serge-Wiki I think, it's good to use `pageType` variable instead of Custom Event which is not present. The extension gives these values:
- `catalog_category_view` for category list
- `catalog_product_view` for product page
- `checkout_cart_index` for shopping cart page etc. You can find those [here](https://github.com/magepal/magento2-googletagmanager/tree/master/view/frontend/layout).

**Comment by magefan** [comment]
@Serge-Wiki event was added in this commit https://github.com/magepal/magento2-googletagmanager/commit/086de3be83d96b51cfd28ae4974f2a319bfc694e

**Comment by Serge-Wiki** [comment]
gediminaskv, 
Thanks for your reply if it’s not hard for you, could you please write the step of how should I set up my Tag and Trigger? Because what I’ve chosen doesn’t provide any data to analytics eCommerce section.

Thanks

**Comment by Serge-Wiki** [comment]
@magefan Thanks, Do you mean I have to update the extension and event will appear on each page?a

**Comment by gediminaskv** [comment]
@Serge-Wiki if it will help you, I share my GTM screenshots: https://qsnapnet.com/folders/32vnckt1oi3mzpv

Also I read some info on https://canonicalized.com/enhanced-ecommerce-tag-manager/?section=product-page and https://zadroweb.com/gtm-data-layer-event-tracking-guide/

**Comment by Serge-Wiki** [comment]
@gediminaskv  I’m very sorry to bather, but still can’t get it right. I’ve updated the extension and created GTM tag (please see the screenshot).

![image](https://user-images.githubusercontent.com/31511015/33289662-4ecd16b2-d3d1-11e7-8fc7-541fe20bf026.png)

I have turned Enhanced E-commerce Tracking in my Google Analytics account, but no data received !

Could you please show me what I miss?

I know that I should see some data in GA under Conversions -> e-commerce, but I see only zeros 

Maybe if possible, you’d write a few steps I should follow in order for this to work properly.

Thanks a lot

**Comment by gewaechshaus** [comment]
@Serge-Wiki - does it work in your case actualy?

**Comment by simonmaass** [comment]
could someone maybe explain a little more detail how to configure your GTM and Analytics in order to get the ecommerce data?
