### ISSUE TITLE
504 Gateway Timeout 

### ISSUE THREAD

**Issue by kauanguesser** [magepal/magento2-google-tag-manager#32]
When i use Google Tag Manager + Reindex i got 504 Gateway Timeout .

Magento 2.2.2

**Comment by srenon** [comment]
Where are you getting a 504?

**Comment by kauanguesser** [comment]
All pages
hortbras.com.br

**Comment by kauanguesser** [comment]
![modules](https://user-images.githubusercontent.com/27354497/34957015-df3104e0-fa12-11e7-802f-9eb3019d7fa9.jpg)
Only this two modules that i installed...

**Comment by srenon** [comment]
I'm 99.99% sure this is not caused by any of those modules, but did you try disabling them and retest to see if the site works?

> The 504 Gateway Timeout error is an HTTP status code that means that one server did not receive a timely response from another server that it was accessing while attempting to load the web page or fill another request by the browser.

> In other words, 504 errors usually indicate that a different computer, one that the website you're getting the 504 message on doesn't control but relies on, isn't communicating with it quickly enough.

Also, the site seems to load for me.
![image](https://user-images.githubusercontent.com/1415141/34957068-fccb4984-f9f9-11e7-9889-6df03fc8fb21.png)

**Comment by kauanguesser** [comment]
I've installed 3 times to check it, and got 504 if install both.

**Comment by kauanguesser** [comment]
If i disable the error keep, i need reinstall the magento.

**Comment by kauanguesser** [comment]
![pagespeed](https://user-images.githubusercontent.com/27354497/34957238-e7dc8f50-fa13-11e7-9816-0bda7a29ea77.jpg)
Google: Time out...

**Comment by srenon** [comment]
This is an issue that I'm not going to be able to solve like this. 

You can open a paid ticket at support@magepal.com and I will have someone fix all your issues.

**Comment by kauanguesser** [comment]
I disabled nginx, it works fine on apache 2.4
