### ISSUE TITLE
Version 1.2.3 Removed from Packagist

### ISSUE THREAD

**Issue by ferrazzuk** [magepal/magento2-google-tag-manager#36]
Looks like you have removed version 1.2.3 of this module from packagist, any reason for this?

#### Magento version #:
Magento 2.1.12

#### Edition (EE, CE, OS, etc):
EE

#### Expected behavior:
Package should be available.

#### Actual behavior:
Package removed?
#### Steps to reproduce:
Require
 "magepal/magento2-googletagmanager": "^1.2"
#### Preconditions

N/A

**Comment by apedicdev** [comment]
same here

**Comment by srenon** [comment]
Sorry... v1.2.3 had few issues related to Full Page Cache and since the newer version is backward compatible I did think anyone was still using it.

**Comment by srenon** [comment]
@apedicdev @ferrazzuk  .... Sorry.,... Please try again

**Comment by apedicdev** [comment]
thank you @srenon we'll consider upgrading

**Comment by ferrazzuk** [comment]
Thank you @srenon
