### ISSUE TITLE
>2.0.7 licence change

### ISSUE THREAD

**Issue by jzahedieh** [magepal/magento2-google-tag-manager#37]
Hi Magepal,

The licence has changed from being open source to proprietary, could you please clarify the limitations and think about including a LICENSE.txt

2.0.7       "OSL-3.0",        "AFL-3.0"
2.1.1         MagePal License
2.2.0        proprietary

Thanks, Jon.

**Comment by srenon** [comment]
@jzahedieh 

All our github modules are free to use.

I changed the license because they were several companies/individuals that would just download our extensions, then doing a find/replace for 'magepal' and remarket the extension as theirs (without even adding/deleting one line of code).
