### ISSUE TITLE
customer-data.js /customer/section/load/?sections=gtm {"message":"gtm section source is not supported"}

### ISSUE THREAD

**Issue by ipascual** [magepal/magento2-google-tag-manager#38]
#### Preconditions
Enable the extension.

<img width="1733" alt="screen shot 2018-05-22 at 11 09 40 am" src="https://user-images.githubusercontent.com/1126559/40375227-ac3764e2-5db0-11e8-8627-763326ae79d7.png">
<img width="891" alt="screen shot 2018-05-22 at 11 09 27 am" src="https://user-images.githubusercontent.com/1126559/40375228-ac67eaa4-5db0-11e8-9484-79a1c6ce2556.png">

**Comment by ipascual** [comment]
It was an error because we were using weltpixel/google-analytics-enhanced-ecommerce-tag-manager-magento-2 and the local storage had that section still after the extension was uninstalled.

**Comment by ipascual** [comment]
Feel free to close it

**Comment by roshanyadav89** [comment]
What is the solution for this???

**Comment by lucafregoso** [comment]
> It was an error because we were using weltpixel/google-analytics-enhanced-ecommerce-tag-manager-magento-2 and the local storage had that section still after the extension was uninstalled.

how did you solve the problem?

**Comment by srenon** [comment]
The best solution will all be base on weather you are run new website or existing website with a lot of returning customer.

In my opinion this is a bug in magento and have review many solution in the past.

You could

1. Delete the local storage (if you don’t have a lot of return in customers)

2. Keep the extension disabled

3. Create a new extension and add the appropriate sections that return blank.

3. Create a plug-in that rewrite how magento handle missing sections


In order to make our extension better, what was the particular reasoning for switching from their extension to ours.

**Comment by lucafregoso** [comment]
> The best solution will all be base on weather you are run new website or existing website with a lot of returning customer. In my opinion this is a bug in magento and have review many solution in the past. You could 1. Delete the local storage (if you don’t have a lot of return in customers) 2. Keep the extension disabled 3. Create a new extension and add the appropriate sections that return blank. 3. Create a plug-in that rewrite how magento handle missing sections In order to make our extension better, what was the particular reasoning for switching from their extension to ours.
> […](#)
> Sent from my iPhone
> On Jul 29, 2021, at 4:39 AM, Luca Fregoso ***@***.***> wrote: ﻿ It was an error because we were using weltpixel/google-analytics-enhanced-ecommerce-tag-manager-magento-2 and the local storage had that section still after the extension was uninstalled. how did you solve the problem? — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

@srenon I'm sorry but I really can't understand what you're saying: why Magento is throwing that exception? how to solve it? I'm working on an existing e-commerce with existing customers.

**Comment by nicholasfishjgm** [comment]
@lucafregoso Did you ever find a fix for this?
