### ISSUE TITLE
Security flaw

### ISSUE THREAD

**Issue by seyuf** [magepal/magento2-google-tag-manager#39]
Why is the plugin sending data to facebook?
```
https://www.facebook.com/tr/?id=148479512476726&ev=PageView&dl=https%3A%2F%2Fwww.XXX.com%2Ffra_eur%2FparkXX-XX-XX-XXXX-iXXXXXXXe-6XXXXXw.html&rl=https%3A%2F%2Fwww.XXXX.com%2Ffra_eur%2FXXX-XXXX-XX-cXX-bachXXX-iXXXle-XXXXXXXw.html&if=false&ts=1530806580852&sw=1920&sh=1080&v=next&r=canary&a=tmgoogletagmanager&ec=0&o=30&ttf=4701.50000000326&tts=4268.199999999022&ttse=4699.899999985471&it=1530806580430
```

#### Magento version #:
2.2.2
#### Edition (EE, CE, OS, etc):
LInux
#### Expected behavior:
Only send data to google
#### Actual behavior:
When enable the plugin tracking data is send to facebook (facebook pixel).
#### Steps to reproduce:
Install and enable the plugin

**Comment by srenon** [comment]
@seyuf... Please provide more information...

Did you check your GTM Admin to see if someone create a facebook tag?

**Comment by seyuf** [comment]
Hi @srenon, you're right no i did not :).
I'll check ASAP.
Thanks.

**Comment by seyuf** [comment]
The client has integrated pixel facebook from the GTM admin.
