### ISSUE TITLE
Invalid block type: MagePal\GoogleTagManager\Block\GtmCode

### ISSUE THREAD

**Issue by thomas-harding** [magepal/magento2-google-tag-manager#43]
Installing MagePal works fine on my staging website, but when I migrate it to a new server, the site goes down with the following error (reduced it down for display purposes)

2 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid block type: MagePal\GoogleTagManager\Block\GtmCode
Exception #1 (ReflectionException): Class MagePal\GoogleTagManager\Block\GtmCode does not exist

Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid block type: MagePal\GoogleTagManager\Block\GtmCode
#0 /var/www/vhosts/usr/htdocs/vendor/magento/framework/View/Layout/Generator/Block.php(249): Magento\Framework\View\Layout\Generator\Block->getBlockInstance('MagePal\\GoogleT...', Array)
#1 /var/www/vhosts/usr/htdocs/vendor/magento/framework/View/Layout/Generator/Block.php(227): Magento\Framework\View\Layout\Generator\Block->createBlock('MagePal\\GoogleT...', 'magepal_gtm_ifr...', Array)
#2 /var/www/vhosts/usr/htdocs/vendor/magento/framework/View/Layout/Generator/Block.php(135): Magento\Framework\View\Layout\Generator\Block->generateBlock(Object(Magento\Framework\View\Layout\ScheduledStructure), Object(Magento\Framework\View\Layout\Data\Structure), 'magepal_gtm_ifr...')
#3 /var/www/vhosts/usr/htdocs/vendor/magento/framework/View/Layout/GeneratorPool.php(80): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))

I use 2.2.4, Open Source.

**Comment by thomas-harding** [comment]
It seems ok now, I've removed it and re-installed via Composer - it's working good now!

**Comment by srenon** [comment]
glad to hear!

Take a look at our [Enhanced E-commerce for Google Tag Manager](https://www.magepal.com/magento2/extensions/enhanced-ecommerce-for-google-tag-manager.html) to take full advantage of Google Analytics
