### ISSUE TITLE
Uncaught ReferenceError: gtag is not defined     at <anonymous>:1:1

### ISSUE THREAD

**Issue by gaurangpadhiyar007** [magepal/magento2-google-tag-manager#50]
#### Preconditions

Please help to resolve this issue;
VM870:1 Uncaught ReferenceError: gtag is not defined
    at <anonymous>:1:1
in the browser console.

**Comment by srenon** [comment]
@gaurangpadhiyar007 .... Please double check your error, there is no reference to "gtag" in this extension

**Comment by gaurangpadhiyar007** [comment]
@srenon 

check below screen shot.
https://www.awesomescreenshot.com/image/3995652/28bf5e51894c07008c4989302720ce5c
I am getting console error which is coming from /magepal/magento2-googletagmanager/view/frontend/templates/gtm_js.phtml

**Comment by srenon** [comment]
99.99% this is not caused by our extension. 

The only thing I can recommend at this point is to open a paid support and I will figure out and fix whatever your issues are. https://www.magepal.com/magento2/extensions/google-tag-manager.html
