### ISSUE TITLE
Data Layer missing Currency Code in magepal-enhanced-ecommerce

### ISSUE THREAD

**Issue by joshiprashiddha** [magepal/magento2-google-tag-manager#51]
#### Steps to reproduce:
1. Add product to cart.
2. Check window.dataLayer at cart page for currencyCode. Will be found for free version but not for paid version for magepal enhanced ecommerce or GTM.

#### Preconditions
1. Magento2 google tag manager installed from magepal.
2. Magento2 enhanced ecommerce installed from magepal.

check paid magepal-enhanced-ecommerce version 1.1.4
`view/frontend/layout/default.xml`
`<argument name="show_ecommerce_currency_code" xsi:type="boolean">false</argument>`
at paid version.

**Comment by srenon** [comment]
A new version will be released soon that correct this...

update 

``` <argument name="show_ecommerce_currency_code" xsi:type="boolean">false</argument>```

to 

```<argument name="show_ecommerce_currency_code" xsi:type="boolean">true</argument>```
