### ISSUE TITLE
Doesn't work on 2.3.1

### ISSUE THREAD

**Issue by twistedindustries** [magepal/magento2-google-tag-manager#52]
#### Magento version #:
2.3.1

#### Edition (EE, CE, OS, etc):
CE

#### Expected behavior:
No JS errors

#### Actual behavior:
Causes JS error on product pages. $.datepicker is undefined

#### Steps to reproduce:
Install normally, refresh product page.

**Comment by srenon** [comment]
`$.datepicker is undefined` is not use in our extension, so base on the limit info this is not a bug in the extension
