### ISSUE TITLE
Google Analytics Blue Tag - Non-standard implementation

### ISSUE THREAD

**Issue by elfeffe** [magepal/magento2-google-tag-manager#57]
I use Magento 2.3.1, with latest version of the extension.
I check my integration using google Tag Assistant in Chrome, it seems to work, but I get a Blue Tag adverting that something is wrong.
It says 
Non-standard implementation
![51714856af0b39fbebc78cacae557df4](https://user-images.githubusercontent.com/4717507/64346073-c6bf3b00-cff1-11e9-8de5-716766a4dbbc.png)

This is the explanation
https://support.google.com/tagassistant/answer/3207128?ref_topic=2947092#nonstandard

Google Analytics is disabled in Magento, I'm just using Google Tag integration.

It's only me?

**Comment by srenon** [comment]
@elfeffe ... To my knowledge, you are the only one having this issue.

To support GDPR, we move the GTM tag code from the header section to a JS (this is the say way Magento does it), which could explain why you set that message.

What I would recommend is to enable debug mode https://support.google.com/tagmanager/answer/6107056?visit_id=637032872041097659-3165837313&rd=1

**Comment by elfeffe** [comment]
Nobody is reporting it because nobody is checking, because the problem is that the script is too far from the head.
Not all of us need GDPR, it must be optional to have it on top or not.
Google Tag manager runs too late for some implementations.

**Comment by srenon** [comment]
I'm thinking about creating an option so if GDPR is off you can choose to include it in the header .... But if you look at Magento Enterprise and even OS they also doing similar logic as we https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/GoogleAnalytics/view/frontend/web/js/google-analytics.js.

**Comment by elfeffe** [comment]
But that’s Google Analytics, not GTM.
It’s not the same, GTM can track things that need to run fast.

**Comment by elfeffe** [comment]
I just saw that the rest of the GTM extension also gives this blue label.
I’m not really sure how bad it is, because it only affects with implementations that need to run very fast.

**Comment by srenon** [comment]
This is how Magneto Enterprise does it ... I will release that will address more of your issue shorty

![image](https://user-images.githubusercontent.com/1415141/68039583-d6ca6280-fca2-11e9-8f31-0fda3a1699de.png)

**Comment by elfeffe** [comment]
I see, sool I will wait for your update. I want to buy the upgrades, I also sent an email to your website asking for the differences, I don't understand what's the datalayer upgrade for example.
I have sent an email to magepal.com

**Comment by srenon** [comment]
GTM - [Google Tag Manager for Magento 2](https://www.magepal.com/magento2/extensions/google-tag-manager.html)
EE - [Enhanced E-commerce for Google Tag Manager](https://www.magepal.com/magento2/extensions/enhanced-ecommerce-for-google-tag-manager.html)
DL - [DataLayer for Google Tag Manager](https://www.magepal.com/magento2/extensions/datalayer-for-google-tag-manager.html)

| Features                    | GTM | EE | DL |
|-----------------------------|:---:|:--:|:--:|
| Global Page Tracking        |  X  |  X |    |
| Order Transaction Tracking  |  X  |  X |    |
| Page Type Event             |     |  X |    |
| Product Clicks              |     |  X |    |
| Product Detail Impressions  |     |  X |    |
| Add to Cart                 |     |  X |    |
| Remove from Cart            |     |  X |    |
| Checkout Steps              |     |  X |    |
| Order Refunds               |     |  X |    |
| Admin Order Tracking        |     |  X |    |
| Access DataLayer using JS   |     |    |  X |
| Bing UET Tracking           |     |    |  X |
| Full Facebook Tracking      |     |    |  X |
| Custom Image Pixel Tracking |     |    |  X |
| Custom iFrame Tracking      |     |    |  X |
| Third-Party Integration     |     |    |  X |

**Comment by elfeffe** [comment]
@srenon Ok, thank you
Does enhance commerce track conversions of configurables by variant? By simple I mean
I'm trying to compare with this one https://www.weltpixel.com/google-analytics-enhanced-ecommerce-tag-manager-magento-2.html

**Comment by Januszpl** [comment]
@srenon as far as I know adding just GTM tag isn't against GDPR. Problem is when it will start to fire tags. Perhaps doing something similar like you did with your dataLayerApi. Create script that can be loaded in GTM tags via 
```
require(['gdpr'], function(gdpr) {
    if (gdpr.isApproved() {
          // some marketing/tracking code snippet
     }
});
```
so it will only execute code inside tags if GDPR mode is enabled and user accepted agreement about cookies.

So one option could be standard way like it is. Second mode would add GTM code to head via server rending (not JS). Then in this mode it would add this GDPR js script I showed above.

Of course if someone doesn't want to follow GDPR then the person doesn't need to add this `require(['gdpr']..... ` part to GTM tag.
