### ISSUE TITLE
add Cart & Customer data before gtm.start (like ecommerce object)

### ISSUE THREAD

**Issue by younes0** [magepal/magento2-google-tag-manager#59]
How can I add cart & customer data in the first object instead of pushing an event "mpCustomerSession" (default module behavior) ?

**this**
![2](https://user-images.githubusercontent.com/886042/68128636-6167c780-ff18-11e9-94e1-887c2de9b201.png)

**instead of**

![1](https://user-images.githubusercontent.com/886042/68128629-5d3baa00-ff18-11e9-9dbb-c03a02750a67.png)

**Comment by srenon** [comment]
@younes0 ... Since Magento use full page cache, customer-specific data is only available after an ajax call.... so the only to get that data is using that event

**Comment by younes0** [comment]
All right, I get it, that makes sense. Thank you.
