### ISSUE TITLE
getGdprOption function returns incorrect values

### ISSUE THREAD

**Issue by Neusta-Hartwig** [magepal/magento2-google-tag-manager#60]
#### Magento version:
2.2.3

#### Edition (EE, CE, OS, etc):
CE

#### Expected behavior:
The Helper function 'getGdprOption' will return the selected option ID for the selected setting in the magento backend (see stores > configuration > magepal > Google Tag Manager)

#### Actual behavior:
The Helper function 'getGdprOption' will returns 1 or 0 as int value for true or false

#### Steps to reproduce:
Check "gdprOption": <?= $block->getGdprOption() ?> in js.pthml for selected option 'Disable Google Analytics Tracking if Cookie Exist' in html source code. Its never option #3, its always #1 

**Fix:**
Use 

`$this->scopeConfig->getValue() 
`
instead of 

`$this->scopeConfig->isSetFlag()`

#### Preconditions
no preconditions

**Comment by srenon** [comment]
This will be fixed in the next version that will be released shortly... Thanks for reporting
