### ISSUE TITLE
Why this needs to be downloaded instead of installed using composer?

### ISSUE THREAD

**Issue by diazwatson** [magepal/magento2-google-tag-manager#65]
A colleague of mine has been advised by Magepal to download the paid enhanced ecommerce which is not available using composer.

Looking at the README in this repo I can also see this:
> ⚠️ Google Tag Manager 2.4.0 has some breaking changes to Enhanced Ecommerce. Please download the latest version of Enhanced Ecommerce 1.4.0 or greater from www.magepal.com account.

I just wonder why the paid enhanced ecommerce module is not available to be installed using composer?

**Comment by srenon** [comment]
@diazwatson ... We are working on our private composer server will be up and running shortly.  In the meantime please download the paid extension from your MagePal account and Manually install it in app/code

**Comment by diazwatson** [comment]
thanks @srenon
