### ISSUE TITLE
Support for PHP 7.3

### ISSUE THREAD

**Issue by diazwatson** [magepal/magento2-google-tag-manager#66]
```
composer require magepal/magento2-enhanced-ecommerce
```
Throws an error saying this module is not compatible with PHP 7.3 which Magento is compatible with from version 2.3.3
#### Edition (EE, CE, OS, etc):
EE, CE
#### Expected behaviour:
Package installs successfully 
#### Actual behavior:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for magepal/magento2-enhanced-ecommerce 1.4.0 -> satisfiable by magepal/magento2-enhanced-ecommerce[1.4.0].
    - magepal/magento2-enhanced-ecommerce 1.4.0 requires php ~5.6.0|7.0.2|7.0.4|~7.0.6|~7.1.0|~7.1.3|~7.2.0 -> your PHP version (7.3.11) does not satisfy that requirement.
```

#### Steps to reproduce:
Installs the module using composer

**Comment by srenon** [comment]
We added a lot of new features and want to roll it out with our new composer server.

To fix this issue can you edit

> /app/code/MagePal/EnhancedEcommerce/composer.json 

and change line number 16 to

> "php": "~5.6.0|7.0.2|7.0.4|~7.0.6|~7.1.0|~7.1.3|~7.2.0|~7.3.0",

**Comment by diazwatson** [comment]
What do you think about deleting the requirement of PHP at all?

Consider this: 
This is a Magento module so it won't work outside Magento, right?

That is why Magento is required in the composer.json
```
"magento/framework": "100.0.*|100.1.*|101.0.*|102.0.*"
```
But Magento already requires php in all these versions :)

**Comment by srenon** [comment]
Good idea!... we may implementing this going forward.

Thanks
