### ISSUE TITLE
Prices of configurable products

### ISSUE THREAD

**Issue by rommelfreddy** [magepal/magento2-google-tag-manager#71]
#### Magento version #: 
Magent CE 2.4.1

#### Edition (EE, CE, OS, etc): 
Magento CE

#### Expected behavior:
Price information for configurable products are correctly set as described by inchoo.
https://inchoo.net/online-marketing/seo-vs-ppc-structured-data-markup-product-variants/

#### Actual behavior:

Please have a look to the image

![Bildschirmfoto 2020-12-04 um 11 19 29](https://user-images.githubusercontent.com/15031079/101152631-a383a100-3623-11eb-939d-d9afb06339d2.png)

Description:

1. This price is the minimum price of the product (incl. special price) --> Should not be precent
2. This price is the minimum price of the product (excl. special price) --> Should be the lowest final price
3. this price is the price without the special price (but the product has a special price) --> should be the final price of the variant
4. this is the (correct) price display on the product detail page.
5. this is the (correct) special price display on the product detail page.
7. this is the (correct) price from the feed - incl.special price. (sorry - wrong product in the screenshot)

#### Steps to reproduce:
none

#### Preconditions
- Configurable products with different prices on the childs incl. special prices.

**Comment by srenon** [comment]
@rommelfreddy .... Not sure I understand your issue because it seem to be related to structure data and not GTM

**Comment by rommelfreddy** [comment]
i am so sorry!
i created the issue in the wrong repository.
