### ISSUE TITLE
Configuration menu not visible after installing the extension 

### ISSUE THREAD

**Issue by AlaaL** [magepal/magento2-google-tag-manager#78]
After installing the extension the configuration menu not appearing 

![image](https://github.com/magepal/magento2-google-tag-manager/assets/5410074/701baba9-e7c4-47a9-bb4d-a02a8a63f989)

Magento 2.3.4#:
Edition CE

I installed it using composer then executed 
setpu:upgrade
setup:di:compile
setup:static-content:deploy -f
clear cache

**Comment by srenon** [comment]
Are you using Mageplaze GTM extension? if so you need to disable it.

**Comment by AlaaL** [comment]
Yes i am, i will try to disable it thank you.

**Comment by AlaaL** [comment]
Thank you it worked but there is something i don't understand if you could help me with or direct me, what i want is to use snapchat pixels in Magento 2 but i did not find any extension specifically to that, and this extension mentioned it can integrate with Snaphchat, but i don't see it in the configuration or am i missing something ?
